services:
  webapp:
    build: .
    ports:
      - "3000:80" # Пробрасываем порт 80 контейнера на порт 3000 хоста
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=OrgDB;User=testerdb;Password=12345;
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: OrgDB
      POSTGRES_USER: testerdb
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432" # Пробрасываем порт 5432 контейнера на порт 5432 хоста
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: